services:
  - type: web
    name: nova-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: 331686735569-42976ac6v02tr7fom0laql915ribrgc5.apps.googleusercontent.com
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
